# -*- coding: utf-8 -*-
"""Hindi_dataset_gen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18s-OT1ZKZhHFaXMoP4B-A8TWB1jdgcuH
"""

import os
import random
import cv2
import pandas as pd
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont,ImageOps
import time

import random
from PIL import Image, ImageDraw, ImageFont

import re
import random
from wordfreq import top_n_list


from PIL import Image, ImageEnhance, ImageFilter
import random
import io
import os
import numpy as np




languages = [
    'English', 'Arabic', 'Chinese', 'French', 'German', 'Hindi', 'Japanese',
    'Telugu', 'Tamil', 'Bengali', 'Sanskrit', 'Malayalam', 'Punjabi', 'Marathi', 'Gujarati'
]




def to_pil(cv2_img):
    return Image.fromarray(cv2.cvtColor(cv2_img, cv2.COLOR_BGR2RGB))

def to_cv2(pil_img):
    return cv2.cvtColor(np.array(pil_img), cv2.COLOR_RGB2BGR)

def apply_noise(image, noise_type):
    if image is None:
        print(f"Warning: Could not read image. Skipping noise type: {noise_type}")
        return None

    pil_img = to_pil(image)
    cv2_img = image.copy()
    h, w = cv2_img.shape[:2]

    if noise_type == "blur":
        return cv2.GaussianBlur(cv2_img, (3, 3), 0)  # reduced from (5,5)



    elif noise_type == "stroke breaks":
        # Create a mask with mostly 1s and few 0s to reduce stroke break intensity
        prob = 0.95  # 95% chance of keeping pixels, 5% break
        mask = (np.random.rand(h, w, 1) < prob).astype(np.uint8)
        mask_3_channel = cv2.merge([mask[:, :, 0]] * 3)
        return cv2_img * mask_3_channel

    elif noise_type == "partial occlusion":
        noisy_img = cv2_img.copy()
        for _ in range(2):
            x1, y1 = random.randint(0, max(0, w-80)), random.randint(0, max(0, h-70))
            x2, y2 = x1 + random.randint(20, 35), y1 + random.randint(20, 35)
            cv2.rectangle(noisy_img, (x1, y1), (x2, y2), (0, 0, 0), -1)
        return noisy_img



    # increased intensity
    elif noise_type == "scanner streaks":
      streak = cv2_img.copy()
      for _ in range(7):  # More streaks
          x = random.randint(0, w - 3)
          color = [random.randint(0, 255) for _ in range(3)]
          streak[:, x:x+2] = color  # Wider streak (2 px)
      return streak
    # changed
    elif noise_type == "printer toner gaps":
      toner = cv2_img.copy()
      center = h // 2
      for _ in range(2):
          offset = random.randint(-30, 30)  # Gap range near center
          y = np.clip(center + offset, 0, max(0, h - 5))  # Ensure within bounds
          toner[y:y+5, :] = [255, 255, 255]  # White horizontal gap
      return toner


    elif noise_type == "horizontal tear":
        y = random.randint(h // 3, 2 * h // 3)
        cv2.line(cv2_img, (0, y), (w, y), (255, 255, 255), thickness=4)
        return cv2_img

    elif noise_type == "vertical tear":
        x = random.randint(w // 3, 2 * w // 3)
        cv2.line(cv2_img, (x, 0), (x, h), (255, 255, 255), thickness=4)
        return cv2_img


    elif noise_type == "double scan":
        shifted = np.roll(cv2_img, random.randint(2, 4), axis=0)
        return cv2.addWeighted(cv2_img, 0.5, shifted, 0.5, 0)



    elif noise_type == "random scratches":
        scratched = cv2_img.copy()
        h, w = scratched.shape[:2]
        for _ in range(random.randint(2, 6)):
            x1 = random.randint(0, w)
            y1 = random.randint(0, h)
            x2 = x1 + random.randint(-w//2, w//2)
            y2 = y1 + random.randint(-h//2, h//2)
            color = (255, 255, 255) if random.random() < 0.5 else (0, 0, 0)
            thickness = random.randint(1, 2)
            cv2.line(scratched, (x1, y1), (x2, y2), color, thickness)
        return scratched

    elif noise_type == "scribble":
        scribbled = cv2_img.copy()
        h, w = scribbled.shape[:2]
        for _ in range(random.randint(1, 3)):
            points = np.array([
                [random.randint(0, w), random.randint(0, h)]
                for _ in range(random.randint(4, 7))
            ], np.int32).reshape((-1, 1, 2))
            color = (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))
            thickness = random.randint(1, 2)
            cv2.polylines(scribbled, [points], False, color, thickness, cv2.LINE_AA)
        return scribbled

    elif noise_type == "staple holes":
      noisy_img = cv2_img.copy()
      h, w = noisy_img.shape[:2]

      num_holes = random.randint(3, 7)
      radius = random.randint(5, 10)

      for _ in range(num_holes):
          position = random.choice([
              (random.randint(0, w//10), random.randint(0, h//10)),                  # top-left
              (random.randint(0, w//10), random.randint(h*9//10, h - 1)),            # bottom-left
              (random.randint(w*9//10, w - 1), random.randint(0, h//10)),            # top-right
              (random.randint(w*9//10, w - 1), random.randint(h*9//10, h - 1)),      # bottom-right
              (random.randint(0, w//10), random.randint(h//3, h*2//3)),              # middle-left
              (random.randint(w*9//10, w - 1), random.randint(h//3, h*2//3))         # middle-right
          ])
          cv2.circle(noisy_img, position, radius, (0, 0, 0), -1)

      return noisy_img
    elif noise_type == "water damage":
      h, w = image.shape[:2]
      blurred = cv2.blur(image, (6, 6))
      mask = np.zeros((h, w), dtype=np.uint8)

      num_spots = 2  # Number of damage spots
      for _ in range(num_spots):
          center = (random.randint(0, w), random.randint(0, h))
          radius = random.randint(20, 45)
          cv2.circle(mask, center, radius, 255, -1)

      mask_3ch = cv2.merge([mask]*3)
      return np.where(mask_3ch == 255, blurred, image)

    elif noise_type == "angled line":
      h, w = image.shape[:2]
      noisy_img = image.copy()

      color = (255, 255, 255) if random.random() > 0.5 else (0, 0, 0)
      thickness =5

      angle = random.uniform(0, 180)
      radians = np.deg2rad(angle)

      # Compute line endpoints so it crosses the image fully
      x0 = int(w / 2 - w * np.cos(radians))
      y0 = int(h / 2 - w * np.sin(radians))
      x1 = int(w / 2 + w * np.cos(radians))
      y1 = int(h / 2 + w * np.sin(radians))

      cv2.line(noisy_img, (x0, y0), (x1, y1), color, thickness)

      return noisy_img
    elif noise_type == "random_erasure":
      h, w = image.shape[:2]
      output = image.copy()
      max_rect = 4
      num_boxes = random.randint(2,3)  # Always at least 3 boxes

      for _ in range(num_boxes):
          x1 = random.randint(0, max(0, w - 10))
          y1 = random.randint(0, max(0, h - 10))

          box_width = random.randint(7, max(8, w // 7))
          box_height = random.randint(5, max(6, h // 6))

          x2 = min(w, x1 + box_width)
          y2 = min(h, y1 + box_height)

          # Randomly choose color: black or white
          color = 0 if random.random() < 0.5 else 255
          output[y1:y2, x1:x2] = color

      return output

    else:
        return cv2_img

type1 = [
    "partial occlusion",
    "horizontal tear",
    "vertical tear",
    "scanner streaks",
    "printer toner gaps",
    # "smudge",
    "stroke breaks",
    # "cutout",
    "double scan",
    "scribble",
    "random scratches",
    "staple holes",
    "water damage",
    "random_erasure",
    "angled line"
]



import random


def generate_mask(clean_img, noisy_img):
    # Resize noisy image to match clean image dimensions (if needed)
    if clean_img.shape != noisy_img.shape:
        noisy_img = cv2.resize(noisy_img, (clean_img.shape[1], clean_img.shape[0]))
        # If clean_img is color and noisy_img is grayscale, convert noisy_img to color
        if len(clean_img.shape) == 3 and len(noisy_img.shape) == 2:
            noisy_img = cv2.cvtColor(noisy_img, cv2.COLOR_GRAY2BGR)
        elif len(clean_img.shape) == 2 and len(noisy_img.shape) == 3:
            clean_img = cv2.cvtColor(clean_img, cv2.COLOR_GRAY2BGR)

    diff = cv2.absdiff(clean_img, noisy_img)
    gray = cv2.cvtColor(diff, cv2.COLOR_BGR2GRAY)

    _, mask = cv2.threshold(gray, 25, 255, cv2.THRESH_BINARY)

    # Convert single-channel binary mask to RGB
    mask_rgb = cv2.cvtColor(mask, cv2.COLOR_GRAY2BGR)
    return mask_rgb



def generate_corrupted_segmentation_mask(clean_mask, noisy_mask):
  
    if clean_mask is None or noisy_mask is None:
        print("❌ One or both masks are None.")
        return None

    if clean_mask.shape != noisy_mask.shape:
        print("❌ Masks have different shapes.")
        return None

    # Invert noisy mask so that noise becomes 0 (black)
    inverse_noisy_mask = cv2.bitwise_not(noisy_mask)

    # Apply bitwise AND to keep only clean text, remove noisy pixels
    corrupted_mask = cv2.bitwise_and(clean_mask, inverse_noisy_mask)

    return corrupted_mask

from PIL import Image
import numpy as np

def get_ism_from_clean_image(clean_image_path, threshold=200):
    # Load and convert to grayscale
    image = Image.open(clean_image_path).convert("L")

    # Convert to NumPy
    image_np = np.array(image)

    # Thresholding: text → white, background → black
    ism_np = np.where(image_np < threshold, 255, 0).astype(np.uint8)

    # Return as RGB NumPy array (3 channels)
    ism_rgb = cv2.cvtColor(ism_np, cv2.COLOR_GRAY2RGB)
    return ism_rgb


metadata = []

languages = [
    'English', 
    'Hindi',
    'Telugu',
      'Tamil', 
    'Bengali', 
    'Malayalam', 
    'Punjabi',
      'Marathi', 
      'Gujarati'
]


bsdt_base_dir="/DATA1/ocrteam/word_restoration/reconstruction/recognition"
# storage_base_dir="/DATA1/ocrteam/word_restoration/reconstruction/test"


df = pd.read_csv(os.path.join(bsdt_base_dir, "test.csv"))


def generate_dataset(
    phrases,
    language,
    clean_output_dir,
    noisy_output_dir,
    bitmask_output_dir,
    ISM_output_dir,
    CSM_output_dir,
):
    print(phrases)
    cnt=2000
    for index,row in phrases.iterrows():
        
        clean_bsdt_path=os.path.join(bsdt_base_dir,row["Filepath"] )
        gt_word=row["Text"]
        clean_img = cv2.imread(clean_bsdt_path)
        clean_path=os.path.join(clean_output_dir,f"{cnt}.png")
        cv2.imwrite(clean_path,clean_img)
        
        #masks
        bitmask_path = os.path.join(bitmask_output_dir, f"{cnt}.png")
        ISM_path=os.path.join(ISM_output_dir, f"{cnt}.png")
        CSM_path=os.path.join(CSM_output_dir, f"{cnt}.png")
        
        image = cv2.imread(clean_path)
        ISM_image = get_ism_from_clean_image(clean_path)
        cv2.imwrite(ISM_path,ISM_image)
        
        #noise apply
        type1_noise = random.choice(type1)
        noisy_img = apply_noise(image, type1_noise)

        mask = generate_mask(image, noisy_img)
        cv2.imwrite(bitmask_path, mask)
        CSM_image = generate_corrupted_segmentation_mask(ISM_image, mask)
        cv2.imwrite(CSM_path, CSM_image)
        
        #save noisy image
        noisy_path = os.path.join(noisy_dir, f"{cnt}.png")
        cv2.imwrite(noisy_path, noisy_img)
        
        metadata.append({
                "code":f"{cnt:05d}",
                "word": gt_word,
                "language": language,
                "word_type":"Scene Text image",
                "text_color": "BSTD",
                "background_color": "BSTD",
                "font_size": "BSTD",
                "font_family": "BSTD",
                "font_style": "BSTD",
                "font_path": "BSTD",
                "noise_type1": type1_noise,
                "noise_type2": "BSTD",
                "noise_type3": "BSTD",
                "angle": "BSTD",
                "clean_path": clean_path,
                "noisy_path": noisy_path,
                "binary_mask_path": bitmask_path,
                "ISM_mask_path":ISM_path,
                "CSM_mask_path":CSM_path
            })

        print(f"✅ {cnt} done")
        cnt += 1
        if cnt>2999:
            break
        
        

for lang in languages: # Upload fonts here
    output_root = f'/DATA1/ocrteam/word_restoration/reconstruction/test2/{lang}_sample_test_dataset'
    print(f"generation Intialized for {output_root}")
    os.makedirs(output_root, exist_ok=True)
    clean_dir = os.path.join(output_root, 'clean')
    noisy_dir = os.path.join(output_root, 'noisy')
    bitmask_dir = os.path.join(output_root, 'bitmask')
    ISM_dir = os.path.join(output_root, 'Intact Segment Mask')
    CSM_dir=os.path.join(output_root, 'Corrupted Segment Mask')
    os.makedirs(clean_dir, exist_ok=True)
    os.makedirs(noisy_dir, exist_ok=True)
    os.makedirs(bitmask_dir, exist_ok=True)
    os.makedirs(ISM_dir, exist_ok=True)
    os.makedirs(CSM_dir, exist_ok=True)
    generate_dataset(
        df[df['Language']==lang.lower()], 
        language=lang,
        clean_output_dir=clean_dir,
        noisy_output_dir=noisy_dir,
        bitmask_output_dir=bitmask_dir,
        ISM_output_dir=ISM_dir,
        CSM_output_dir=CSM_dir,
        )




output_root_csv = '/DATA1/ocrteam/word_restoration/reconstruction/test2'
metadata_csv_path = os.path.join(output_root_csv, "BDST_test_image.csv")
df = pd.DataFrame(metadata)
df.to_csv(metadata_csv_path, index=False)
print(f"📄 Metadata saved to {metadata_csv_path}")







# metadata.append({
#             "code":f"{cnt:05d}",
#             "word": phrase,
#             "language": language,
#             "word_type":"BSTD",
#             "text_color": text_color,
#             "background_color": bg_color,
#             "font_size": font_size,
#             "font_family": font_family,
#             "font_style": Path(font_path).stem.replace(" ","_").split("_")[0],
#             "font_path": font_path,
#             "noise_type1": type1_noise,
#             "noise_type2": type2_noise,
#             "noise_type3": type3_noise,
#             "angle": rotation_angle,
#             "clean_path": clean_path,
#             "noisy_path": noisy_path,
#             "binary_mask_path": bitmask_path
#         })